# Generated by Django 3.1.5 on 2021-01-31 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poonnanun', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contract',
            new_name='Contact',
        ),
    ]
